# Generated by Django 4.0.1 on 2022-02-08 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(max_length=200, verbose_name='Display Name')),
                ('play_music', models.BooleanField(default=True, verbose_name='Play Music?')),
            ],
        ),
        migrations.CreateModel(
            name='TopScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Score')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NeoCrosser.account')),
            ],
        ),
        migrations.CreateModel(
            name='GameSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField(verbose_name='JSON Save')),
                ('is_live', models.BooleanField(default=False, verbose_name='Can Join?')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NeoCrosser.account')),
            ],
        ),
    ]
