# Generated by Django 4.0.1 on 2022-02-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NeoCrosser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topscore',
            name='question_text',
        ),
        migrations.AddField(
            model_name='topscore',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='NeoCrosser.account'),
            preserve_default=False,
        ),
    ]
