# Generated by Django 4.0.1 on 2022-04-19 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(max_length=200, verbose_name='Display Name')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=200, verbose_name='Word')),
                ('length', models.IntegerField(verbose_name='Length')),
                ('double_letters', models.BooleanField(default=False, verbose_name='Does the word have double letters?')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup', models.CharField(max_length=200, verbose_name='Cup Name')),
                ('guesses', models.IntegerField(verbose_name='Guesses taken to solve')),
                ('time', models.IntegerField(verbose_name='Time in seconds taken to solve')),
                ('sub_date', models.DateTimeField(verbose_name='Date Submitted')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordle.account')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordle.word')),
            ],
        ),
    ]
