# Generated by Django 4.0.1 on 2022-04-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='common',
            field=models.BooleanField(default=False, verbose_name='Is it a (sort of) common word?'),
        ),
    ]
