# Generated by Django 4.0.1 on 2022-03-01 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Compition Name')),
                ('guesses', models.IntegerField(verbose_name='Guesses')),
                ('time', models.IntegerField(verbose_name='Time in seconds')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordle.account')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordle.word')),
            ],
        ),
    ]
