# Generated by Django 4.0.1 on 2022-03-10 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0002_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='sub_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 10, 17, 39, 12, 860654, tzinfo=utc), verbose_name='Date Submitted'),
        ),
    ]
