# Generated by Django 4.0.1 on 2022-03-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0003_score_sub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='sub_date',
            field=models.DateTimeField(verbose_name='Date Submitted'),
        ),
    ]
