# Generated by Django 4.0.1 on 2022-03-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0004_alter_score_sub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='word',
        ),
        migrations.AddField(
            model_name='score',
            name='word',
            field=models.ManyToManyField(to='wordle.Word'),
        ),
    ]
