# Generated by Django 4.0.1 on 2022-04-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0005_remove_score_word_score_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='name',
        ),
        migrations.RemoveField(
            model_name='word',
            name='doubleLetters',
        ),
        migrations.AddField(
            model_name='score',
            name='cup',
            field=models.CharField(default=5, max_length=200, verbose_name='Cup Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='double_letters',
            field=models.BooleanField(default=False, verbose_name='Does the word have double letters?'),
        ),
        migrations.AlterField(
            model_name='score',
            name='guesses',
            field=models.IntegerField(verbose_name='Guesses taken to solve'),
        ),
        migrations.AlterField(
            model_name='score',
            name='time',
            field=models.IntegerField(verbose_name='Time in seconds taken to solve'),
        ),
    ]
