# Generated by Django 4.0.1 on 2022-02-02 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='Username')),
                ('display_name', models.CharField(max_length=200, verbose_name='Display Name')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('play_music', models.BooleanField(default=True, verbose_name='Play Music?')),
            ],
        ),
        migrations.CreateModel(
            name='TopScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('score', models.IntegerField(verbose_name='Score')),
            ],
        ),
        migrations.CreateModel(
            name='GameSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField(verbose_name='JSON Save')),
                ('is_live', models.BooleanField(default=False, verbose_name='Can Join?')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NeoCrosser.account')),
            ],
        ),
    ]
